-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 14:20:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema invernaderoBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `invernaderoBD` ;

-- -----------------------------------------------------
-- Schema invernaderoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invernaderoBD` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `invernaderoBD` ;

-- -----------------------------------------------------
-- Table `invernaderoBD`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`usuario` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(15) NOT NULL,
  `contrasenia` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `correo_electronico_UNIQUE` ON `invernaderoBD`.`usuario` (`correo_electronico` ASC);

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `invernaderoBD`.`usuario` (`usuario` ASC);


-- -----------------------------------------------------
-- Table `invernaderoBD`.`calibracion_infiltrometro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`calibracion_infiltrometro` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`calibracion_infiltrometro` (
  `id_calibracion_infiltrometro` INT NOT NULL AUTO_INCREMENT,
  `presion` FLOAT NOT NULL,
  PRIMARY KEY (`id_calibracion_infiltrometro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invernaderoBD`.`calibracion_frente_humedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`calibracion_frente_humedad` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`calibracion_frente_humedad` (
  `id_calibracion_frentehum` INT NOT NULL AUTO_INCREMENT,
  `impedancia_uno_real` FLOAT NOT NULL,
  `impedancia_uno_imaginaria` FLOAT NOT NULL,
  `impedancia_dos_real` FLOAT NOT NULL,
  `impedancia_dos_imaginaria` FLOAT NOT NULL,
  `impedancia_tres_real` FLOAT NOT NULL,
  `impedancia_tres_imaginaria` FLOAT NOT NULL,
  `impedancia_cuatro_real` FLOAT NOT NULL,
  `impedancia_cuatro_imaginaria` FLOAT NOT NULL,
  `impedancia_cinco_real` FLOAT NOT NULL,
  `impedancia_cinco_imaginaria` FLOAT NOT NULL,
  `impedancia_seis_real` FLOAT NOT NULL,
  `impedancia_seis_imaginaria` FLOAT NOT NULL,
  `impedancia_siete_real` FLOAT NOT NULL,
  `impedancia_siete_imaginaria` FLOAT NOT NULL,
  `impedancia_ocho_real` FLOAT NOT NULL,
  `impedancia_ocho_imaginaria` FLOAT NOT NULL,
  PRIMARY KEY (`id_calibracion_frentehum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invernaderoBD`.`detalle_calibracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`detalle_calibracion` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`detalle_calibracion` (
  `iddetalle_calibracion` INT NOT NULL AUTO_INCREMENT,
  `fecha_calibracion` DATETIME NOT NULL,
  `calibracion_infiltrometro` INT NOT NULL,
  `calibracion_frentehum` INT NOT NULL,
  PRIMARY KEY (`iddetalle_calibracion`),
  CONSTRAINT `id_calibracion_infiltrometro`
    FOREIGN KEY (`calibracion_infiltrometro`)
    REFERENCES `invernaderoBD`.`calibracion_infiltrometro` (`id_calibracion_infiltrometro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_calibracion_frentehum`
    FOREIGN KEY (`calibracion_frentehum`)
    REFERENCES `invernaderoBD`.`calibracion_frente_humedad` (`id_calibracion_frentehum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_calibracion_infiltrometro_idx` ON `invernaderoBD`.`detalle_calibracion` (`calibracion_infiltrometro` ASC);
CREATE INDEX `id_calibracion_frentehum_idx` ON `invernaderoBD`.`detalle_calibracion` (`calibracion_frentehum` ASC);

-- -----------------------------------------------------
-- Table `invernaderoBD`.`experimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`experimento` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`experimento` (
  `id_experimento` INT NOT NULL AUTO_INCREMENT,
  `nombre_experimento` VARCHAR(250) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `periodo_muestreo` INT NOT NULL,
  `voltaje` FLOAT NOT NULL,
  `frecuencia` INT NOT NULL,
  `estado_experimento` TINYINT NOT NULL,
  `usuario` INT NOT NULL,
  `detalle_calibracion` INT NOT NULL,
  PRIMARY KEY (`id_experimento`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `invernaderoBD`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iddetalle_calibracion`
    FOREIGN KEY (`detalle_calibracion`)
    REFERENCES `invernaderoBD`.`detalle_calibracion` (`iddetalle_calibracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_experimento_UNIQUE` ON `invernaderoBD`.`experimento` (`nombre_experimento` ASC);

CREATE INDEX `id_usuario_idx` ON `invernaderoBD`.`experimento` (`usuario` ASC);

CREATE INDEX `iddetalle_calibracion_idx` ON `invernaderoBD`.`experimento` (`detalle_calibracion` ASC);


-- -----------------------------------------------------
-- Table `invernaderoBD`.`fecha_de_sensado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`fecha_de_sensado` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`fecha_de_sensado` (
  `id_fecha` INT NOT NULL AUTO_INCREMENT,
  `fecha_sensado` DATE NOT NULL,
  `hora_sensado` VARCHAR(45) NOT NULL,
  `id_experimento` INT NOT NULL,
  PRIMARY KEY (`id_fecha`),
  CONSTRAINT `id_experimento`
    FOREIGN KEY (`id_experimento`)
    REFERENCES `invernaderoBD`.`experimento` (`id_experimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_experimento_idx` ON `invernaderoBD`.`fecha_de_sensado` (`id_experimento` ASC);


-- -----------------------------------------------------
-- Table `invernaderoBD`.`infiltrometro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`infiltrometro` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`infiltrometro` (
  `id_infiltrometro` INT NOT NULL AUTO_INCREMENT,
  `presion` FLOAT NOT NULL,
  `fecha_sensado` INT NOT NULL,
  PRIMARY KEY (`id_infiltrometro`),
  CONSTRAINT `id_fecha`
    FOREIGN KEY (`fecha_sensado`)
    REFERENCES `invernaderoBD`.`fecha_de_sensado` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_fecha_idx` ON `invernaderoBD`.`infiltrometro` (`fecha_sensado` ASC);


-- -----------------------------------------------------
-- Table `invernaderoBD`.`higrometro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`higrometro` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`higrometro` (
  `id_higr` INT NOT NULL AUTO_INCREMENT,
  `sensor_uno` FLOAT NULL COMMENT '	',
  `sensor_dos` FLOAT NULL,
  `sensor_tres` FLOAT NULL,
  `sensor_cuatro` FLOAT NULL,
  `sensor_cinco` FLOAT NULL,
  `sensor_seis` FLOAT NULL,
  `sensor_siete` FLOAT NULL,
  `sensor_ocho` FLOAT NULL,
  `sensor_nueve` FLOAT NULL,
  `sensor_diez` FLOAT NULL,
  `resistividad` FLOAT NULL,
  `fecha_sensado` INT NOT NULL,
  PRIMARY KEY (`id_higr`),
  CONSTRAINT `id_fechahigr`
    FOREIGN KEY (`fecha_sensado`)
    REFERENCES `invernaderoBD`.`fecha_de_sensado` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_fechahigr_idx` ON `invernaderoBD`.`higrometro` (`fecha_sensado` ASC);


-- -----------------------------------------------------
-- Table `invernaderoBD`.`frente_de_humedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invernaderoBD`.`frente_de_humedad` ;

CREATE TABLE IF NOT EXISTS `invernaderoBD`.`frente_de_humedad` (
  `id_frente_humedad` INT NOT NULL AUTO_INCREMENT,
  `impedancia_uno_real` FLOAT NULL,
  `impedancia_uno_imaginaria` FLOAT NULL,
  `impedancia_dos_real` FLOAT NULL,
  `impedancia_dos_imaginaria` FLOAT NULL,
  `impedancia_tres_real` FLOAT NULL,
  `impedancia_tres_imaginara` FLOAT NULL,
  `impedancia_cuatro_real` FLOAT NULL,
  `impedancia_cuatro_imaginaria` FLOAT NULL,
  `impedancia_cinco_real` FLOAT NULL,
  `impedancia_cinco_imaginaria` FLOAT NULL,
  `impedancia_seis_real` FLOAT NULL,
  `impedancia_seis_imaginaria` FLOAT NULL,
  `impedancia_siete_real` FLOAT NULL,
  `impedancia_siete_imaginaria` FLOAT NULL,
  `impedancia_ocho_real` FLOAT NULL,
  `impedancia_ocho_imaginaria` FLOAT NULL,
  `temperatura_uno` FLOAT NULL,
  `temperatura_dos` FLOAT NULL,
  `temperatura_tres` FLOAT NULL,
  `temperatura_cuatro` FLOAT NULL,
  `temperatura_cinco` FLOAT NULL,
  `temperatura_seis` FLOAT NULL,
  `temperatura_siete` FLOAT NULL,
  `temperatura_ocho` FLOAT NULL,
  `fecha_sensado` INT NOT NULL,
  PRIMARY KEY (`id_frente_humedad`),
  CONSTRAINT `id_fechafrente`
    FOREIGN KEY (`fecha_sensado`)
    REFERENCES `invernaderoBD`.`fecha_de_sensado` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_fechafrente_idx` ON `invernaderoBD`.`frente_de_humedad` (`fecha_sensado` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;